---
- name: Install neofetch
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'min'
          - os_family

    - name: Install neofetch on Debian
      ansible.builtin.apt:
        name: neofetch
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
      become: true

    - name: Install neofetch on Redhat
      ansible.builtin.dnf:
        name: neofetch
        state: present
      when: ansible_facts['os_family'] == 'Redhat'
      become: true
