---
- name: Install neofetch
  hosts: all
  gather_facts: true

  tasks:
    - name: Install neofetch
      ansible.builtin.apt:
        name: neofetch
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
