---
- name: Install neofetch
  hosts: all
  gather_facts: true

  tasks:
    - name: Install neofetch on Debian
      ansible.builtin.apt:
        name: neofetch
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

  tasks:
    - name: Install neofetch on Redhat
      ansible.builtin.dnf:
        name: neofetch
        state: present
      when: ansible_facts['os_family'] == 'Redhat'
