- name: Install latest qemu-guest-agent package
  hosts: all
  become: yes

  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.dnf:
        name: qemu-guest-agent
        state: present
        update_cache: true
